### ISSUE TITLE
Failed to excute "python prepare_data.py --user {snowdream} --verbose"

### ISSUE THREAD

**Issue by snowdream** [EverythingMe/openspace#2]
```
$ python prepare_data.py --user {snowdream} --verbose
[05/04/2015 15:10:18 INFO] in prepare_data.get_repos_from_github:30: Fetching user info for {snowdream}
Traceback (most recent call last):
  File "prepare_data.py", line 175, in <module>
    main()
  File "d:\bin\Python34\lib\site-packages\click\core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "d:\bin\Python34\lib\site-packages\click\core.py", line 644, in main
    rv = self.invoke(ctx)
  File "d:\bin\Python34\lib\site-packages\click\core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\bin\Python34\lib\site-packages\click\core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "d:\bin\Python34\lib\site-packages\click_config\__init__.py", line 122, in wrapper
    return fn(**kwargs_to_forward)
  File "prepare_data.py", line 147, in main
    github_repos = get_repos_from_github(user)
  File "prepare_data.py", line 35, in get_repos_from_github
    public_repos_count = user_data['public_repos']
KeyError: 'public_repos'
```

**Comment by maticrivo** [comment]
Hey you should run the command without {}.
It should be:

``` python
python prepare_data.py --user snowdream --verbose
```

**Comment by snowdream** [comment]
@maticrivo 

```
$ python prepare_data.py --user snowdream --verbose
[05/04/2015 15:43:08 INFO] in prepare_data.get_repos_from_github:30: Fetching user info for snowdream
[05/04/2015 15:43:10 INFO] in prepare_data.get_repos_from_github:42: Fetching repo info for 54 repos
Traceback (most recent call last):
  File "prepare_data.py", line 175, in <module>
    main()
  File "d:\bin\Python34\lib\site-packages\click\core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "d:\bin\Python34\lib\site-packages\click\core.py", line 644, in main
    rv = self.invoke(ctx)
  File "d:\bin\Python34\lib\site-packages\click\core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\bin\Python34\lib\site-packages\click\core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "d:\bin\Python34\lib\site-packages\click_config\__init__.py", line 122, in wrapper
    return fn(**kwargs_to_forward)
  File "prepare_data.py", line 147, in main
    github_repos = get_repos_from_github(user)
  File "prepare_data.py", line 44, in get_repos_from_github
    for page in range(1, public_repos_count / PAGE_SIZE + 2):
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by joeysim** [comment]
Thanks.

I've updated the README file and removed curly brackets from param placeholders.
I've also fixed the casting to integer and import to be python3 safe.

Cheers
